### ISSUE TITLE
RES Firefox unhide comments doesn't draw collapsers

### ISSUE THREAD

**Issue by tom-james-watson** [tom-james-watson/reddit-comment-collapser#9]
https://www.reddit.com/r/firefox/comments/5xw5ba/reddit_comment_collapser_my_addon_for_making/dem8gyn/

Bug report: Unfortunately doesn't work when you have RES set to "automatically hide all child comments". When you expand a comment tree the lines are not drawn.

Hunch would be observer isn't working.

**Comment by marcii** [comment]
It wouldn't be the observer, since the comments are already loaded, they're just hidden.

This happens because the width is set for each collapser element when they're created. If they're hidden, the midcol'ss offsetWidth is 0 and they're fixed to that even after they're unhidden.

Could base the dimensions for all elements on the first valid comment's (i.e. not collapsed or deleted) midcol.
